/**
 * Cross-language conformance test (EXP-08's "deliverable's spine").
 *
 * `scripts/generate_conformance_fixtures.py` runs the real Python
 * `sprout.answer.Assistant` over every question in `eval/suites/*.yaml` (the same
 * question set the eval harness scores against) *and* every corpus-derived case in the
 * Phase 1 smoke suite, and records its answer. This test replays every one of those
 * questions through the TypeScript port loaded from the same exported
 * `index.json`/`config.json` bundle, and asserts the two implementations agree exactly:
 * same rendered text, same citations, same confidence, same confidence *band*, same
 * refusal reason. Any drift here is a real bug in the port, not a fixture staleness
 * issue, as long as `make web-static-fixtures` was re-run after the last Python pipeline
 * change (CI does this — see `.github/workflows/ci.yml`).
 *
 * A field this suite does not compare is a field the two implementations are free to
 * disagree on. That is not hypothetical: `confidence_band` and `confidence_band_label`
 * (EXP-06) were absent from the port entirely — the server UI announced "well-supported
 * (0.82)" and the static site announced "82% confidence" — and every case here passed,
 * because the comparison covered the float the port had and not the words derived from
 * it.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import assert from "node:assert/strict";
import { test } from "node:test";

import { Assistant } from "../src/answer.js";
import { VectorStore } from "../src/store.js";
import { assertBundleIsCurrent, bundleAsOfDisplay } from "../src/config.js";
import type { WebConfig } from "../src/config.js";
import { answerCitations, answerDisplayText, answerText, type Answer } from "../src/models.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
// This file compiles to dist/test/conformance.test.js, so the package root (where
// public/data/*.json and test/fixtures/*.json live, uncompiled) is two levels up.
const ROOT = path.resolve(HERE, "..", "..");

interface FixtureCase {
  id: string;
  suite: string;
  question: string;
  language_requested: string;
  expected: {
    language: string;
    refused: boolean;
    refusal_reason: string | null;
    text: string;
    display_text: string;
    citations: string[];
    confidence: number;
    confidence_band: string;
    confidence_band_label: string;
    low_confidence: boolean;
    abstained: boolean;
    is_safety_query: boolean;
    safety_notice: string | null;
    disclosure: string;
    as_of: string | null;
  };
}

interface FixtureFile {
  format_version: number;
  cases: FixtureCase[];
}

function loadJson<T>(relPath: string): T {
  return JSON.parse(readFileSync(path.join(ROOT, relPath), "utf-8")) as T;
}

const config = loadJson<WebConfig>("public/data/config.json");
const indexJson = loadJson<unknown>("public/data/index.json");
const fixtures = loadJson<FixtureFile>("test/fixtures/conformance.json");

const store = VectorStore.fromIndexJson(indexJson);
const assistant = new Assistant(config, store);

// Version 1 fixtures record no confidence band, so replaying them would assert nothing
// about it while this file reads as though it does — refuse them rather than compare
// `undefined` against `undefined` and call that agreement.
assert.equal(fixtures.format_version, 2, "unexpected fixture format version");
assert.ok(fixtures.cases.length > 0, "no conformance fixtures loaded");

// The fixture set is the hand-authored eval suites plus the corpus-derived smoke suite.
// If the smoke half ever stops being generated the remaining cases still all pass, and
// the suite would report full agreement over a question set that quietly halved.
assert.ok(
  fixtures.cases.some((c) => c.suite === "smoke"),
  "no corpus-derived smoke cases in the fixtures — re-run `make web-static-fixtures`",
);

// The fixtures were generated by Python from one corpus; this suite replays them against
// the bundle in `public/data/`. If that bundle is a stale export the mismatches would be
// reported as port bugs, which is precisely the misdiagnosis the provenance block exists
// to prevent — so refuse to run against a bundle that cannot say which corpus it is.
// `sprout bundle-check` is the check that the fingerprint is the *right* one; this is the
// check that there is one at all.
assertBundleIsCurrent(config);
assert.notEqual(bundleAsOfDisplay(config.provenance), "unknown", "bundle has no usable as-of date");

for (const fixture of fixtures.cases) {
  test(`conformance: ${fixture.suite}/${fixture.id}`, () => {
    const answer: Answer = assistant.answer(fixture.question, fixture.language_requested);
    const expected = fixture.expected;

    assert.equal(answer.language, expected.language, "language");
    assert.equal(answer.refused, expected.refused, "refused");
    assert.equal(answer.refusal_reason, expected.refusal_reason, "refusal_reason");
    assert.equal(answerText(answer), expected.text, "text");
    assert.equal(answerDisplayText(answer), expected.display_text, "display_text");
    assert.deepEqual(
      answerCitations(answer).map((c) => c.chunk_id),
      expected.citations,
      "citations",
    );
    assert.equal(answer.confidence, expected.confidence, "confidence");
    assert.equal(answer.confidence_band, expected.confidence_band, "confidence_band");
    assert.equal(
      answer.confidence_band_label,
      expected.confidence_band_label,
      "confidence_band_label",
    );
    assert.equal(answer.low_confidence, expected.low_confidence, "low_confidence");
    assert.equal(answer.abstained, expected.abstained, "abstained");
    assert.equal(answer.is_safety_query, expected.is_safety_query, "is_safety_query");
    assert.equal(answer.safety_notice, expected.safety_notice, "safety_notice");
    assert.equal(answer.disclosure, expected.disclosure, "disclosure");
    assert.equal(answer.as_of, expected.as_of, "as_of");
  });
}
